version: "3.6"
services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=...
      - MYSQL_PASSWORD=...
    image: ghcr.io/fluxfw/ilias-mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/log/mysql:/var/log/mysql
  ilias:
    depends_on:
      - mysql
    environment:
      - ILIAS_COMMON_MASTER_PASSWORD=...
      - ILIAS_CRON_USER_PASSWORD=...
      - ILIAS_DATABASE_PASSWORD=...
      - ILIAS_HTTP_PATH=http://%host_ip%
      - ILIAS_LUEANCE_SEARCH=true
      - ILIAS_ROOT_USER_PASSWORD=...
      - ILIAS_SMTP_HOST=smtp
      - ILIAS_SMTP_PORT=1025
      - ILIAS_SYSTEMFOLDER_CONTACT_FIRSTNAME=...
      - ILIAS_SYSTEMFOLDER_CONTACT_LASTNAME=...
      - ILIAS_SYSTEMFOLDER_CONTACT_EMAIL=...
    image: ghcr.io/fluxfw/ilias-dev:php7.4
    volumes:
      - ./ilias:/var/www/html
      - ./data/ilias:/var/iliasdata
      - ./data/log/ilias:/var/log/ilias
      - ./data/log/xdebug:/var/log/xdebug
  nginx:
    depends_on:
      - ilias
    image: ghcr.io/fluxfw/ilias-nginx:1.20
    ports:
      - %host_ip%:80:80
    volumes:
      - ./ilias:/var/www/html
      - ./data/ilias/web:/var/iliasdata/web
      - ./data/log/nginx:/var/log/nginx
  cron:
    depends_on:
      - ilias
    environment:
      - ILIAS_CRON_USER_PASSWORD=...
    image: ghcr.io/fluxfw/ilias-cron-dev:php7.4
    volumes:
      - ./ilias:/var/www/html
      - ./data/ilias:/var/iliasdata
      - ./data/log/ilias:/var/log/ilias
      - ./data/log/xdebug:/var/log/xdebug
  ilserver:
    depends_on:
      - ilias
    image: ghcr.io/fluxfw/ilias-ilserver:java8
    volumes:
      - ./ilias:/var/www/html
      - ./data/ilias:/var/iliasdata
      - ./data/log/ilserver:/var/log/ilserver
  chatroom:
    depends_on:
      - ilias
    image: ghcr.io/fluxfw/ilias-chatroom:nodejs10
    ports:
      - %host_ip%:8080:8080
    volumes:
      - ./ilias:/var/www/html
      - ./data/ilias:/var/iliasdata
      - ./data/log/chatroom:/var/log/chatroom
  smtp:
    image: mailhog/mailhog:latest
    ports:
      - %host_ip%:8025:8025
