version: "3.6"
services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=...
      - MYSQL_PASSWORD=...
    image: docker-registry.fluxpublisher.ch/flux-ilias/mysql:5.7
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/log/mysql:/var/log/mysql
  ilias:
    depends_on:
      - mysql
    environment:
      - ILIAS_COMMON_MASTER_PASSWORD=...
      - ILIAS_DATABASE_PASSWORD=...
      - ILIAS_HTTP_PATH=https://%host_ip%
      - ILIAS_ROOT_USER_PASSWORD=...
      - ILIAS_SYSTEMFOLDER_CONTACT_FIRSTNAME=...
      - ILIAS_SYSTEMFOLDER_CONTACT_LASTNAME=...
      - ILIAS_SYSTEMFOLDER_CONTACT_EMAIL=...
    image: docker-registry.fluxpublisher.ch/flux-ilias/ilias:php7.4
    restart: always
    volumes:
      - ./ilias:/var/www/html
      - ./data/ilias:/var/iliasdata
      - ./data/log/ilias:/var/log/ilias
  nginx:
    depends_on:
      - ilias
    environment:
      - ILIAS_NGINX_HTTPS_CERT=/certs/ilias.crt
      - ILIAS_NGINX_HTTPS_KEY=/certs/ilias.key
      - ILIAS_NGINX_HTTPS_DHPARAM=/certs/ilias.pem
    image: docker-registry.fluxpublisher.ch/flux-ilias/nginx:latest
    ports:
      - [%host_ip%:]80:80
      - [%host_ip%:]443:443
    restart: always
    volumes:
      - ./ilias:/var/www/html
      - ./data/ilias/web:/var/iliasdata/web
      - ./data/log/nginx:/var/log/nginx
      - ./data/certs:/certs:ro
